new scripts

diff --git a/s3/bash-scripts/put-objects b/s3/bash-scripts/put-objects
--- a/s3/bash-scripts/put-objects
+++ b/s3/bash-scripts/put-objects
@@ -1,1 +1,28 @@
 #!/usr/bin/env bash
+echo "==put objects"
+#exit immedeatily when a cmand returns non-zero status
+set -e
+#where we will store the files
+OUTPUT_DIR="/tmp/s3-bash-scripts"
+
+
+#remove folder if already exists
+rm -r $OUTPUT_DIR
+
+#create a output directory
+mkdir -p $OUTPUT_DIR
+
+#generate a random number
+# to determine how many files to create
+
+NUM_FILES=$((RANDOM % 6 + 5))
+
+for ((i=1; i<=$NUM_FILES; i++)); do
+    #generate random file name
+    FILENAME="$OUTPUT_DIR/file_$i.txt"
+
+    #generate random data and write to the files
+    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 2024 +1 ))2>/dev/null
+done
+
+tree $OUTPUT_DIR
diff --git a/s3/bash-scripts/sync b/s3/bash-scripts/sync
--- a/s3/bash-scripts/sync
+++ b/s3/bash-scripts/sync
@@ -1,1 +1,46 @@
 #!/usr/bin/env bash
+echo "==sync"
+#exit immedeatily when a cmand returns non-zero status
+set -e
+# Check if the first argument is provided
+if [ -z "$1" ]; then
+    echo "There. needs to be bucket name eg ./bucket my-bucket-name."
+    exit 1
+fi
+
+
+# Check if the second argument (file name) is provided
+if [ -z "$2" ]; then
+    echo "There. needs to be bucket name eg ./bucket my-bucket-name."
+    exit 1
+fi
+
+BUCKET_NAME=$1
+FILENAME_PREFIX=$2
+
+#where we will store the files
+OUTPUT_DIR="/tmp/s3-bash-scripts"
+
+
+#remove folder if already exists
+rm -r $OUTPUT_DIR
+
+#create a output directory
+mkdir -p $OUTPUT_DIR
+
+#generate a random number
+# to determine how many files to create
+
+NUM_FILES=$((RANDOM % 6 + 5))
+
+for ((i=1; i<=$NUM_FILES; i++)); do
+    #generate random file name
+    FILENAME="$OUTPUT_DIR/$FILENAME_PREFIX_$i.txt"
+
+    #generate random data and write to the files
+    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 2024 +1 ))2>/dev/null
+done
+
+tree $OUTPUT_DIR
+
+aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME
